"""Function-based API for dataset operations.

This module provides standalone functions that wrap the HuwiseDataset
class internally for simpler use cases.

Note:
    For complex workflows or multiple field updates, consider using
    the HuwiseDataset class directly for method chaining.
"""

from huwise_utils_py._legacy.getters import (
    get_all_dataset_ids,
    get_dataset_accrualperiodicity,
    get_dataset_contact_email,
    get_dataset_contact_name,
    get_dataset_contributor,
    get_dataset_created,
    get_dataset_creator,
    get_dataset_custom_view,
    get_dataset_dcat_ap_ch_license,
    get_dataset_dcat_ap_ch_rights,
    get_dataset_description,
    get_dataset_geographic_reference,
    get_dataset_issued,
    get_dataset_keywords,
    get_dataset_language,
    get_dataset_license,
    get_dataset_metadata,
    get_dataset_metadata_temporal_period,
    get_dataset_modified,
    get_dataset_publisher,
    get_dataset_relation,
    get_dataset_theme,
    get_dataset_title,
    get_number_of_datasets,
    get_template_metadata,
    get_uid_by_id,
)
from huwise_utils_py._legacy.setters import (
    set_dataset_accrualperiodicity,
    set_dataset_contact_email,
    set_dataset_contact_name,
    set_dataset_contributor,
    set_dataset_created,
    set_dataset_creator,
    set_dataset_dcat_ap_ch_license,
    set_dataset_dcat_ap_ch_rights,
    set_dataset_description,
    set_dataset_geographic_reference,
    set_dataset_issued,
    set_dataset_keywords,
    set_dataset_language,
    set_dataset_license,
    set_dataset_metadata_temporal_coverage_end_date,
    set_dataset_metadata_temporal_coverage_start_date,
    set_dataset_metadata_temporal_period,
    set_dataset_modified,
    set_dataset_public,
    set_dataset_publisher,
    set_dataset_relation,
    set_dataset_theme,
    set_dataset_title,
    set_template_metadata,
)

__all__ = [
    # Getters
    "get_all_dataset_ids",
    "get_dataset_accrualperiodicity",
    "get_dataset_contact_email",
    "get_dataset_contact_name",
    "get_dataset_contributor",
    "get_dataset_created",
    "get_dataset_creator",
    "get_dataset_custom_view",
    "get_dataset_dcat_ap_ch_license",
    "get_dataset_dcat_ap_ch_rights",
    "get_dataset_description",
    "get_dataset_geographic_reference",
    "get_dataset_issued",
    "get_dataset_keywords",
    "get_dataset_language",
    "get_dataset_license",
    "get_dataset_metadata",
    "get_dataset_metadata_temporal_period",
    "get_dataset_modified",
    "get_dataset_publisher",
    "get_dataset_relation",
    "get_dataset_theme",
    "get_dataset_title",
    "get_number_of_datasets",
    "get_template_metadata",
    "get_uid_by_id",
    # Setters
    "set_dataset_accrualperiodicity",
    "set_dataset_contact_email",
    "set_dataset_contact_name",
    "set_dataset_contributor",
    "set_dataset_created",
    "set_dataset_creator",
    "set_dataset_dcat_ap_ch_license",
    "set_dataset_dcat_ap_ch_rights",
    "set_dataset_description",
    "set_dataset_geographic_reference",
    "set_dataset_issued",
    "set_dataset_keywords",
    "set_dataset_language",
    "set_dataset_license",
    "set_dataset_metadata_temporal_coverage_end_date",
    "set_dataset_metadata_temporal_coverage_start_date",
    "set_dataset_metadata_temporal_period",
    "set_dataset_modified",
    "set_dataset_public",
    "set_dataset_publisher",
    "set_dataset_relation",
    "set_dataset_theme",
    "set_dataset_title",
    "set_template_metadata",
]
