#!/usr/bin/env python3
"""Discover theme_id mappings for a Huwise domain.

This script uses the Automation API to list all datasets on your domain,
collects the unique ``internal.theme_id`` values alongside their human-readable
theme names from the Explore API, and outputs a ``THEME_MAP`` dictionary that
you can use in your own code.

Usage:
    Set the environment variables ``HUWISE_API_KEY`` and ``HUWISE_DOMAIN``
    (see .env.example), then run::

        uv run python scripts/discover_themes.py

    Or with explicit arguments::

        uv run python scripts/discover_themes.py --domain data.bs.ch --api-key YOUR_KEY

The script outputs a Python dict mapping theme hash IDs to human-readable names,
e.g.::

    THEME_MAP = {
        "7b5b405": "Verwaltung",
        "06af88d": "Bevoelkerung",
        ...
    }

Note:
    Theme IDs are platform-internal hashes and are **domain-specific**.
    The mapping generated by this script is only valid for the domain it was
    run against.  Different Huwise instances will have different theme IDs.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import httpx
from dotenv import load_dotenv

load_dotenv()


def _automation_headers(api_key: str) -> dict[str, str]:
    return {
        "Authorization": f"apikey {api_key}",
        "Content-Type": "application/json",
    }


def _get_all_datasets(domain: str, api_key: str) -> list[dict]:
    """Paginate through all datasets via the Automation API."""
    base_url = f"https://{domain}/api/automation/v1.0/datasets/"
    headers = _automation_headers(api_key)
    datasets: list[dict] = []
    offset = 0
    limit = 100

    with httpx.Client(timeout=30) as client:
        while True:
            resp = client.get(
                base_url,
                headers=headers,
                params={"limit": limit, "offset": offset},
            )
            resp.raise_for_status()
            data = resp.json()
            results = data.get("results", [])
            datasets.extend(results)
            if data.get("next") is None or len(results) == 0:
                break
            offset += limit

    return datasets


def _get_explore_themes(domain: str) -> dict[str, list[str]]:
    """Fetch human-readable theme names per dataset from the Explore API.

    Returns a mapping of ``dataset_uid`` to a list of theme names.
    """
    base_url = f"https://{domain}/api/explore/v2.1/catalog/datasets"
    uid_to_names: dict[str, list[str]] = {}
    offset = 0
    limit = 100

    with httpx.Client(timeout=30) as client:
        while True:
            resp = client.get(
                base_url,
                params={
                    "select": "dataset_uid,theme",
                    "limit": limit,
                    "offset": offset,
                },
            )
            resp.raise_for_status()
            data = resp.json()
            results = data.get("results", [])
            for ds in results:
                uid = ds.get("dataset_uid", "")
                themes = ds.get("theme", [])
                if uid and themes:
                    uid_to_names[uid] = themes if isinstance(themes, list) else [themes]
            if len(results) < limit:
                break
            offset += limit

    return uid_to_names


def _ensure_list(value: str | list[str]) -> list[str]:
    """Normalise a metadata value that may be a string or list into a list."""
    if isinstance(value, str):
        return [value]
    return value


def _collect_theme_ids(datasets: list[dict]) -> dict[str, list[str]]:
    """Extract ``internal.theme_id`` per dataset from Automation API results.

    Returns a mapping of ``dataset_uid`` to a list of theme hash IDs.
    """
    uid_to_ids: dict[str, list[str]] = {}
    for ds in datasets:
        uid = ds.get("uid", "")
        metadata = ds.get("metadata", {})
        internal = metadata.get("internal", {})
        theme_ids = _ensure_list(internal.get("theme_id", {}).get("value", []))
        if uid and theme_ids:
            uid_to_ids[uid] = theme_ids
    return uid_to_ids


def discover_themes(domain: str, api_key: str) -> dict[str, str]:
    """Build a mapping of theme hash IDs to human-readable names.

    Strategy:
    1. Fetch all datasets from the **Automation API** to get
       ``internal.theme_id`` per dataset.
    2. Fetch all datasets from the **Explore API** to get human-readable
       theme names per dataset.
    3. Match by ``dataset_uid`` and pair IDs with names positionally.
    """
    print(f"Fetching datasets from Automation API ({domain})...")
    datasets = _get_all_datasets(domain, api_key)
    print(f"  Found {len(datasets)} datasets.")

    uid_to_ids = _collect_theme_ids(datasets)
    print(f"  Collected theme IDs from {len(uid_to_ids)} datasets.")

    print(f"Fetching theme names from Explore API ({domain})...")
    uid_to_names = _get_explore_themes(domain)
    print(f"  Collected theme names from {len(uid_to_names)} datasets.")

    # Pair IDs with names by matching dataset_uid
    theme_map: dict[str, str] = {}
    unknown_ids: set[str] = set()

    for uid, ids in uid_to_ids.items():
        names = uid_to_names.get(uid, [])
        for i, tid in enumerate(ids):
            if tid and tid not in theme_map:
                if i < len(names) and names[i]:
                    theme_map[tid] = names[i].strip()
                else:
                    unknown_ids.add(tid)

    if unknown_ids:
        remaining = unknown_ids - set(theme_map.keys())
        if remaining:
            print(f"Note: {len(remaining)} theme IDs could not be resolved:")
            for tid in sorted(remaining):
                print(f"  - {tid}")
                theme_map[tid] = f"<unknown: {tid}>"

    return theme_map


def main() -> None:
    parser = argparse.ArgumentParser(description="Discover theme_id mappings for a Huwise domain.")
    parser.add_argument(
        "--domain",
        default=os.environ.get("HUWISE_DOMAIN"),
        help="Huwise domain (e.g. data.bs.ch). Defaults to HUWISE_DOMAIN env var.",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("HUWISE_API_KEY"),
        help="API key for the Automation API. Defaults to HUWISE_API_KEY env var.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output as JSON instead of Python dict.",
    )
    args = parser.parse_args()

    if not args.domain:
        print("Error: --domain or HUWISE_DOMAIN env var is required.", file=sys.stderr)
        sys.exit(1)
    if not args.api_key:
        print("Error: --api-key or HUWISE_API_KEY env var is required.", file=sys.stderr)
        sys.exit(1)

    theme_map = discover_themes(args.domain, args.api_key)

    print(f"\nDiscovered {len(theme_map)} themes:\n")

    if args.json:
        print(json.dumps(theme_map, indent=2, ensure_ascii=False))
    else:
        print("THEME_MAP = {")
        for tid, name in sorted(theme_map.items(), key=lambda x: x[1]):
            print(f'    "{tid}": "{name}",')
        print("}")


if __name__ == "__main__":
    main()
